spring.config.import=classpath:env.properties

mongodb.url=${mongodb.connection.url}
mongodb.database=spendTracker
mongodb.collection=dailyTracker

tracker.info.filepath= src\\main\\resources\\file.csv
spring.data.jpa.repositories.enabled=false